apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: grpc-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: grpc-client
  template:
    metadata:
      labels:
        app.kubernetes.io/component: grpc-client
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: grpc-client
          image: viacheslave/grpcclient:latest
          command: ["sleep", "3600"]